routes/web.php
<?php

use App\Models\Transaction;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});
Route::get('/about', function () {
    return view('landing.about');
});

Route::get('/service', function () {
    return view('landing.service');
});

Route::get('/contact', function () {
    return view('landing.contact');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function(){

    Route::resource('catalog', App\Http\Controllers\CatalogController::class);
    Route::resource('book', App\Http\Controllers\BookController::class);
    Route::resource('publisher', App\Http\Controllers\PublisherController::class);
    Route::resource('writer', App\Http\Controllers\WriterController::class);
    Route::resource('member', App\Http\Controllers\MemberController::class);
    Route::resource('transaction', App\Http\Controllers\TransactionController::class);
    Route::resource('role_permissions', \App\Http\Controllers\RolePermissionController::class);
    // api url
    Route::get('get/writer', [\App\Http\Controllers\WriterController::class, 'getData']);
    Route::get('get/publisher', [\App\Http\Controllers\PublisherController::class, 'getData']);
    Route::get('get/member', [\App\Http\Controllers\MemberController::class, 'getData']);
    Route::get('get/book', [\App\Http\Controllers\BookController::class, 'getData']);
    Route::get('get/transaction', [\App\Http\Controllers\TransactionController::class, 'getData']);

});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Member;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $books;
    protected $members;

    public function  __construct()
    {
        $this->members = Member::all();
        $this->books = Book::where('stock', '>', 0)->get();
    }

    public function index()
    {
        // $this->authorize('lihat data peminjaman');
        return view('admin.transactions.index');
    }

    public function getData(Request $request)
    {
        // jika ada request status
        if ( $request->status) {
            // parsing terlebih dahulu nilai status menjadi boolean
            $status = ($request->status == 'selesai') ? boolval(1) : boolval(0) ;
            // ambil data peminjaman berdasarkan status yang sudah diparsing
            $transactions = Transaction::where('status',  $status )->get();
        // jika ada request start_date
        } elseif ($request->start_date) {
            // ambil data peminajaman yang tanggal pinjamnya antara request start_date dan end_date.
            $transactions = Transaction::whereBetween('start', [$request->start_date, $request->end_date])->get();
        // selebihnya
        } else {
            // ambil semua data peminjaman
            $transactions = Transaction::orderBy('id', 'desc')->get();
        }

        // buat datatable dari data peminjaman hasil filter dari fungsi di atas
        $datatables = Datatables::of($transactions)
                    // tambahkan kolom action untuk tombol edit, detail, dan hapus
                    ->addColumn('action', function($transactions) {
                        $btnEdit = '<a href="'.route('transaction.edit', ['transaction' => $transactions->id] ).'" class="btn-sm btn-primary">Edit</a>';
                        $btnDetail = '<a href="'.url('transaction/'. $transactions->id).'" class="btn-sm mx-1 btn-info">Detail</a>';
                        $btnDelete = "<a href='#' onclick='app.destroy(event, $transactions->id)' class='btn-sm btn-danger'> Delete</a>";
                        return '<div class="btn-group" role="group" aria-label="Basic example">' . $btnEdit . $btnDetail . $btnDelete . '</div>';
                    })
                    // tambahkan kolom member
                    ->addColumn('member', function($transactions) {
                        return $transactions->member->name;
                    })
                    // tambahkan kolom quantity
                    ->addColumn('quantity', function($transactions) {
                        return $transactions->books->sum('pivot.qty');
                    })
                    // tambahkan kolom total_payment
                    ->addColumn('total_payment', function($transactions) {
                        // ambil jumlah record data dari kolom qty pada tabel pivot (tranaction_details) * jumlah harga pada setiap buku
                        $total_payment = $transactions->books->sum('pivot.qty') * $transactions->books->sum('price'); // model = many to many (pivot = transaction_details)
                        return "Rp " .  number_format($total_payment, 0, ',', '.') . ",00";
                    })
                    // tambahkan kolom period
                    ->addColumn('period', function($transactions) {
                        // ambil selisih hari di antara kolom start dan end
                        $range = dateDifference($transactions->start, $transactions->end);
                        return $range;
                    })
                    // tambahkan kolom start
                    ->editColumn('start', function($transactions) {
                        // ambil data start dan parsing data dengan helper yang sudah dibuat sendiri ( custom_date() ).
                        return custom_date($transactions->start);
                    })
                    ->editColumn('end', function($transactions) {
                        // ambil data end dan parsing data dengan helper yang sudah dibuat sendiri ( custom_date() ).
                        return custom_date($transactions->end);
                    })
                    //  tambahkan kolom status
                    ->editColumn('status', function($transactions) {
                        $status = ($transactions->status == 1) ? "selesai" : "dalam proses" ;
                        return $status;
                    })
                    ->removeColumn(['member_id', 'created_at', 'updated_at']) // hapus kolom member_id
                    ->addIndexColumn() // tambahkan index kolom [0, 1, 2, dst...]
                    ->make(true);

        return $datatables;

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $members = $this->members;
        $books = $this->books;
        return view('admin.transactions.create', compact('members', 'books'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreTransactionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // lakukan validasi request
        $request->validate([
            'member_id' => 'required',
            'start' => 'required',
            'end' => 'required',
            'book_id' => 'required',
        ]);

        // inisialisasi model transaction
        $transaction = new Transaction();

        // input data dari request yang dikirimkan
        # mengisi tabel utama (transactions tabel)
        $transaction->start = date('Y-m-d', strtotime($request->start));
        $transaction->end = date('Y-m-d', strtotime($request->end));
        $transaction->member_id = $request->member_id;
        $transaction->status = false;
        $transaction->save();

        # isi tabel pivot (transaction_details)
        // isi kolom book_id dengan request (book_id) yang dikirimkan berserta dengan kolm qty dengan nilai 1.
        $transaction->books()->attach($request->book_id, ['qty' => 1]);

        // update stock buku
        foreach ($request->book_id as $id) {
            $book = Book::find($id); // ambil data buku yang ID-nya = nilai ke-n dalam pengulangan ini.
            $book->stock -= 1; // ubah data pada kolom stok dengan - 1
            $book->save(); // simpan data
        }

        return redirect('transaction')->with('success', 'Yeeaayy, Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {

        return view('admin.transactions.detail', compact('transaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {

        $members = $this->members;
        $buku = $this->books;
        return view('admin.transactions.edit', compact('transaction', 'members', 'buku'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateTransactionRequest  $request
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
         // lakukan validasi request
         $request->validate([
            'member_id' => 'required',
            'start' => 'required',
            'end' => 'required',
            'book_id' => 'required',
        ]);

        // isi data dari request yang dikirimkan
        # isi tabel utama (transactions tabel)
        $transaction->start = date('Y-m-d', strtotime($request->start));
        $transaction->end = date('Y-m-d', strtotime($request->end));
        $transaction->member_id = $request->member_id;
        $transaction->status = $request->status;
        $transaction->update();

        $transaction->refresh();
        # isi tabel pivot (transaction_details)
        // isi kolom book_id dengan request (book_id) yang dikirimkan berserta dengan kolm qty dengan nilai 1.
        $transaction->books()->syncWithPivotValues($request->book_id, ['qty' => 1]);
        // syncWithPivotValues($array_value, ['pivot' => value]) berfungsi untuk menghapus record transaksi terkait di tabel pivot dan menggantinya dengan yang data yang baru

        // update stock buku
        foreach ($request->book_id as $id) {
            $book = Book::find($id); // ambil data buku yang ID-nya = nilai ke-n dalam pengulangan ini.

            if ($request->status == 1) {
                $book->stock += 1; // ubah data pada kolom stok dengan - 1
            } else {
                $book->stock -= 1; // ubah data pada kolom stok dengan - 1
            }

            $book->update(); // simpan data
        }

        return redirect('transaction')->with('success', 'Yeeaayy, Data Berhasil Diubah');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        $transaction->books()->detach();
        $transaction->delete();
        return response()->json($transaction);
    }
}

resources/views/admin/transactions/create.blade.php
@extends('layouts.app')

@section("content-header", "Peminjaman")
@section("title", "Peminjaman")
@section('subtitle', 'Tambah Peminjaman')
@section('content-title', 'Tambah Peminjaman' )

@section('content')
<div class="row justify-content-center">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header bg-primary">
                <h4 class="card-title">Tambah Peminjaman Baru</h4>
            </div>
            <div class="card-body">
                <form action="{{route('transaction.store')}}" method="POST">
                    @csrf
                    <div class="mb-3">
                      <label for="member_id" class="form-label">Peminjam</label>
                      <select class="form-control @error('member_id') is-invalid @enderror" name="member_id" id="member_id">
                          <option value="">--Pilih--</option>
                          @foreach ($members as $member)
                          <option value="{{$member->id}}">{{$member->name}}</option>
                          @endforeach
                      </select>
                      @error('member_id')
                          <small class="text-danger">{{$message}}</small>
                      @enderror
                    </div>
                    <div class="row">
                        <div class="col-2">
                            <label>Tanggal</label>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                    <input type="text" class="form-control datetimepicker-input" data-target="#reservationdate" name="start" value="{{old('start')}}"/>
                                    <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            @error('start')
                                <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                        <div class="col-1 text-center">
                            <span><b>s/d</b></span>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <div class="input-group date" id="reservationdate2" data-target-input="nearest">
                                    <input type="text" class="form-control datetimepicker-input" data-target="#reservationdate2" name="end" value="{{old('end')}}"/>
                                    <div class="input-group-append" data-target="#reservationdate2" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            @error('end')
                                <small class="text-danger">{{$message}}</small>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Buku</label>
                        <select class="select2" multiple="multiple" data-placeholder="Masukan Buku" style="width: 100%;" name="book_id[]">
                            @foreach ($books as $book)
                                <option value="{{$book->id}}">{{$book->title}}</option>
                            @endforeach
                        </select>
                        @error('book_id')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a href="{{route('transaction.index')}}" class="btn btn-secondary">Batal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('css')
<!-- daterange picker -->
<link rel="stylesheet" href="{{asset('vendor/plugins/daterangepicker/daterangepicker.css')}}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{{asset('vendor/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet" href="{{asset('vendor/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css')}}">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{{asset('vendor/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('vendor/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('vendor/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
<!-- Bootstrap4 Duallistbox -->
<link rel="stylesheet" href="{{asset('vendor/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css')}}">
<!-- BS Stepper -->
<link rel="stylesheet" href="{{asset('vendor/plugins/bs-stepper/css/bs-stepper.min.css')}}">
<!-- dropzonejs -->
<link rel="stylesheet" href="{{asset('vendor/plugins/dropzone/min/dropzone.min.css')}}">

@endsection

@push('script')
<!-- Select2 -->
<script src="{{asset('vendor/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{{asset('vendor/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js')}}"></script>
<!-- InputMask -->
<script src="{{asset('vendor/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('vendor/plugins/inputmask/jquery.inputmask.min.js')}}"></script>
<!-- date-range-picker -->
<script src="{{asset('vendor/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- bootstrap color picker -->
<script src="{{asset('vendor/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('vendor/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Bootstrap Switch -->
<script src="{{asset('vendor/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
<!-- BS-Stepper -->
<script src="{{asset('vendor/plugins/bs-stepper/js/bs-stepper.min.js')}}"></script>
<!-- dropzonejs -->
<script src="{{asset('vendor/plugins/dropzone/min/dropzone.min.js')}}"></script>

<!-- Page specific script -->
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date picker start
    $('#reservationdate').datetimepicker({
        format: 'L'
    });
    //Date picker end
    $('#reservationdate2').datetimepicker({
        format: 'L'
    });

    //Date and time picker
    $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datetimepicker({
      format: 'LT'
    })

    //Bootstrap Duallistbox
    $('.duallistbox').bootstrapDualListbox()

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    $('.my-colorpicker2').on('colorpickerChange', function(event) {
      $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
    })

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    })

  })
  // BS-Stepper Init
  document.addEventListener('DOMContentLoaded', function () {
    window.stepper = new Stepper(document.querySelector('.bs-stepper'))
  })

  // DropzoneJS Demo Code Start
  Dropzone.autoDiscover = false

  // Get the template HTML and remove it from the doumenthe template HTML and remove it from the doument
  var previewNode = document.querySelector("#template")
  previewNode.id = ""
  var previewTemplate = previewNode.parentNode.innerHTML
  previewNode.parentNode.removeChild(previewNode)

  var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
    url: "/target-url", // Set the url
    thumbnailWidth: 80,
    thumbnailHeight: 80,
    parallelUploads: 20,
    previewTemplate: previewTemplate,
    autoQueue: false, // Make sure the files aren't queued until manually added
    previewsContainer: "#previews", // Define the container to display the previews
    clickable: ".fileinput-button" // Define the element that should be used as click trigger to select files.
  })

  myDropzone.on("addedfile", function(file) {
    // Hookup the start button
    file.previewElement.querySelector(".start").onclick = function() { myDropzone.enqueueFile(file) }
  })

  // Update the total progress bar
  myDropzone.on("totaluploadprogress", function(progress) {
    document.querySelector("#total-progress .progress-bar").style.width = progress + "%"
  })

  myDropzone.on("sending", function(file) {
    // Show the total progress bar when upload starts
    document.querySelector("#total-progress").style.opacity = "1"
    // And disable the start button
    file.previewElement.querySelector(".start").setAttribute("disabled", "disabled")
  })

  // Hide the total progress bar when nothing's uploading anymore
  myDropzone.on("queuecomplete", function(progress) {
    document.querySelector("#total-progress").style.opacity = "0"
  })

  // Setup the buttons for all transfers
  // The "add files" button doesn't need to be setup because the config
  // `clickable` has already been specified.
  document.querySelector("#actions .start").onclick = function() {
    myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED))
  }
  document.querySelector("#actions .cancel").onclick = function() {
    myDropzone.removeAllFiles(true)
  }
  // DropzoneJS Demo Code End
</script>
@endpush

resources/views/admin/transactions/detail.blade.php
@extends('layouts.app')

@section("content-header", "Peminjaman")
@section("title", "Peminjaman")
@section('subtitle', 'Detail Peminjaman')
@section('content-title', 'Detail Peminjaman' )

@section('content')
<div class="row justify-content-center">
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header bg-primary">
                <h4 class="card-title">Detail Peminjaman</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6 my-2">
                        Nama Anggota
                    </div>
                    <div class="col-6 my-2">
                        : {{$transaction->member->name}}
                    </div>
                    <div class="col-6">
                        Tanggal
                    </div>
                    <div class="col-6">
                        : {{ custom_date($transaction->start) }} - {{ custom_date($transaction->end) }}
                    </div>
                    <div class="col-6 my-2">
                        Buku yang dipinjam
                    </div>
                    <div class="col-6 my-2">:
                            @foreach ($transaction->books as $book)
                                <span class="badge badge-info">{{$book->title}}</span>
                            @endforeach
                    </div>
                    <div class="col-6 my-2">
                        Status
                    </div>
                    <div class="col-6 my-2">:
                        @if ($transaction->status == 1)
                            Sudah dikembalikan
                        @else
                            Belum dikembalikan
                        @endif
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="{{ url()->previous() }}" class="btn btn-secondary">Kembali</a>
            </div>
        </div>
    </div>
</div>
@endsection