routes/web.php
<?php

use App\Models\Transaction;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});
Route::get('/about', function () {
    return view('landing.about');
});

Route::get('/service', function () {
    return view('landing.service');
});

Route::get('/contact', function () {
    return view('landing.contact');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware('auth')->group(function(){

    Route::resource('catalog', App\Http\Controllers\CatalogController::class);
    Route::resource('book', App\Http\Controllers\BookController::class);
    Route::resource('publisher', App\Http\Controllers\PublisherController::class);
    Route::resource('writer', App\Http\Controllers\WriterController::class);
    Route::resource('member', App\Http\Controllers\MemberController::class);
    Route::resource('transaction', App\Http\Controllers\TransactionController::class);
    Route::resource('role_permissions', \App\Http\Controllers\RolePermissionController::class);
    // api url
    Route::get('get/writer', [\App\Http\Controllers\WriterController::class, 'getData']);
    Route::get('get/publisher', [\App\Http\Controllers\PublisherController::class, 'getData']);
    Route::get('get/member', [\App\Http\Controllers\MemberController::class, 'getData']);
    Route::get('get/book', [\App\Http\Controllers\BookController::class, 'getData']);
    Route::get('get/transaction', [\App\Http\Controllers\TransactionController::class, 'getData']);

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <link rel="icon" type="image/x-icon" href="{{asset('img/prams_brand.png')}}">

  <title>{{ config('app.name', 'Laravel') }} | @yield('title')</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('vendor/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('vendor/dist/css/adminlte.min.css')}}">

  @yield('css')

</head>

<body class="hold-transition sidebar-mini layout-navbar-fixed">
<!-- Site wrapper -->
    <div class="wrapper">
        {{-- navbar --}}
        @include('layouts.navbar')
        {{-- navbar end --}}

        {{-- sidebar --}}
        @include('layouts.sidebar')
        {{-- sidebar end --}}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>@yield('content-header')</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">@yield('title')</a></li>
                            <li class="breadcrumb-item active">@yield('subtitle')</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </section>

            <!-- Main content -->
            <section class="content px-5">
                @yield('content')
            </section>
            <!-- /.content -->

        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <strong>Copyright &copy; 2021 pramono.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{{asset('vendor/plugins/jquery/jquery.min.js')}}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{asset('vendor/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('vendor/dist/js/adminlte.min.js')}}"></script>

    @stack('script')
</body>
</html>

resources/views/layouts/landing.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <!-- mobile responsive meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{{asset('vendor/landing/plugins/bootstrap/bootstrap.min.css')}}">
        <!-- themefy-icon -->
        <link rel="stylesheet" href="{{asset('vendor/landing/plugins/themify-icons/themify-icons.css')}}">
        <!-- slick slider -->
        <link rel="stylesheet" href="{{asset('vendor/landing/plugins/slick/slick.css')}}">
        <!-- venobox popup -->
        <link rel="stylesheet" href="{{asset('vendor/landing/plugins/Venobox/venobox.css')}}">
        <!-- aos -->
        <link rel="stylesheet" href="{{asset('vendor/landing/plugins/aos/aos.css')}}">

        <!-- Main Stylesheet -->
        <link href="{{asset('vendor/landing/css/style.css')}}" rel="stylesheet">
        <!--Favicon-->
        <link rel="shortcut icon" href="{{asset('vendor/landing/images/favicon.ico')}}" type="image/x-icon">
        <link rel="icon" href="{{asset('vendor/landing/images/favicon.ico')}}" type="image/x-icon">

        <style>
            body {
                font-family: 'Nunito', sans-serif;
            }
        </style>
    </head>
<body>
    <section class="fixed-top navigation">
        <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <h4 class="brand">SISTEM MANAJEMEN PERPUSTAKAAN</h4>
            <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <!-- navbar -->
            <div class="collapse navbar-collapse text-center" id="navbar">
                @if (Route::has('login'))
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{url('/')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{{url('/#feature')}}">Fitur</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url('about')}}">Tentang</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{{url('/#team')}}">Developer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url('/contact')}}">Kontak</a>
                    </li>
                    @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{url('/home')}}">Dashboard</a>
                    </li>
                    @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('login')}}">Masuk</a>
                    </li>
                    </ul>
                    @endauth
                    @endif
                </div>
            </nav>
        </div>
    </section>

    @yield('content')

    <!-- footer -->
    <footer class="footer-section footer" style="background-image: url({{asset('vendor/landing/images/backgrounds/footer-bg.png')}});">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 text-center text-lg-left mb-4 mb-lg-0">
                    <h5>Sistem Manajemen Perpustakaan</h5>
                </div>
                <!-- footer menu -->
                <nav class="col-lg-8 align-self-center mb-5">
                    <ul class="list-inline text-lg-right text-center footer-menu">
                        <li class="list-inline-item active"><a href="{{url('/')}}">Home</a></li>
                        <li class="list-inline-item"><a class="page-scroll" href="{{url('/#feature')}}">Fitur</a></li>
                        <li class="list-inline-item"><a href="{{url('about')}}">Tentang</a></li>
                        <li class="list-inline-item"><a class="page-scroll" href="{{url('/#team')}}">Developer</a></li>
                        <li class="list-inline-item"><a href="{{url('/contact')}}">Kontak</a></li>
                    </ul>
                </nav>
                <!-- footer social icon -->
                <nav class="col-12">
                <ul class="list-inline text-lg-right text-center social-icon">
                    <li class="list-inline-item">
                        <a class="facebook" href="#"><i class="ti-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="linkedin" href="#"><i class="ti-linkedin"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="black" href="#"><i class="ti-github"></i></a>
                    </li>
                </ul>
                </nav>
            </div>
        </div>
    </footer>
  <!-- /footer -->

  <!-- jQuery -->
  <script src="{{asset('vendor/landing/plugins/jQuery/jquery.min.js')}}"></script>
  <!-- Bootstrap JS -->
  <script src="{{asset('vendor/landing/plugins/bootstrap/bootstrap.min.js')}}"></script>
  <!-- slick slider -->
  <script src="{{asset('vendor/landing/plugins/slick/slick.min.js')}}"></script>
  <!-- venobox -->
  <script src="{{asset('vendor/landing/plugins/Venobox/venobox.min.js')}}"></script>
  <!-- aos -->
  <script src="{{asset('vendor/landing/plugins/aos/aos.js')}}"></script>
  <!-- Main Script -->
  <script src="{{asset('vendor/landing/js/script.js')}}"></script>
  @stack('script')
</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    @guest
        @if (Route::has('login'))

        <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>

        @endif

        @if (Route::has('register'))

        <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
        </li>

        @endif
    @else
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                @if (count(pinjamanTelat()))
                <span class="badge badge-warning navbar-badge">{{ count(pinjamanTelat()) }}</span>
                @endif
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <span class="dropdown-item dropdown-header">Pengembalian Telat</span>
            <div class="dropdown-divider"></div>
            @foreach (pinjamanTelat() as $data)
            <a href="{{ route( 'transaction.show', ['transaction' => $data['transaction'] ] )}}" class="dropdown-item">
                <i class="fas fa-book mr-2"></i> {{ $data["member"] }}
                <span class="float-right text-muted text-sm">{{ $data["delay"] }} Hari</span>
            </a>
            <div class="dropdown-divider"></div>
            @endforeach
                @if (count(pinjamanTelat()))
                    <a href="#" class="dropdown-item dropdown-footer">Total {{ count(pinjamanTelat()) }} data</a>
                @else
                    <a href="#" class="dropdown-item dropdown-footer">belum ada data</a>
                @endif
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                    <i class="fas fa-power-off text-danger"></i>
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </li>
        </ul>
    @endguest
</nav>

resources/views/layouts/sidebar.blade.php
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{url('/')}}" class="brand-link">
      <img src="{{asset('img/prams_brand.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">{{ config('app.name', 'Laravel') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="#" class="d-block">{{ucwords(Auth::user()->name)}}</a>
        </div>
      </div>
      <!-- SidebarSearch Form -->
      <div class="form-inline">
        
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
                <a href="{{url('/home')}}" class="nav-link {{ request()->is('home') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{url('/transaction')}}" class="nav-link {{ request()->is('transaction') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-shopping-cart"></i>
                    <p>Peminjaman</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{url('/member')}}" class="nav-link {{ request()->is('member') ? 'active' : '' }}">
                    <i class="fas fa-id-card-alt nav-icon"></i>
                    <p>Anggota</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{url('/book')}}" class="nav-link {{ request()->is('book') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-book"></i>
                    <p>Buku</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{url('/catalog')}}" class="nav-link {{ request()->is('catalog') ? 'active' : '' }}">
                    <i class="nav-icon fas fa-list"></i>
                    <p>Katalog</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{url('/publisher')}}" class="nav-link {{ request()->is('publisher') ? 'active' : '' }}">
                    <i class="fas fa-globe-asia nav-icon"></i>
                    <p>Penerbit</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{url('/writer')}}" class="nav-link {{ request()->is('writer') ? 'active' : '' }}">
                    <i class="fas fa-feather nav-icon"></i>
                    <p>Pengarang</p>
                </a>
            </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>